### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by osyed** [hayes/unpm#76]
Using version 1.3.3 of unpm.
My config.json has 
    "fallback": "http://registry.npmjs.org/"

When I try:
    npm install yaml

I get the error:
    Registry returned 500 for GET on http://10.0.0.157:8123/yaml

The unpm logs show:
{"name":"unpm","hostname":"x","pid":4906,"level":30,"statusCode":500,"method":"GET","url":"/yaml","msg":"","time":"2015-05-11T17:40:16.360Z","v":0}

If I try:
    curl http://10.0.0.157:8123/yaml

I get the error:
    {"code":"InternalError","message":"Cannot read property 'headers' of undefined"}

If I try:
    curl http://registry.npmjs.org/

I get response like:
    {"db_name":"registry","doc_count":157498, .... }

So it seems my host can connect to http://registry.npmjs.org/ and fallback is setup to use the public registry. I'm not sure what is causing the error. Any ideas?

**Comment by hayes** [comment]
Interesting... a few things happening here.

Simple fix: remove the trailing '/' from the fallback url, everything should work fine.

Looks like I am not properly joining paths for the fallback url, I'll try to get that fixed asap.  currently unpm forwards on whatever response it gets from the fallback, the error you are seeing is from http://registry.npmjs.com//yaml which I have reported to the folks over at npm since it seems like it should probably be handled differently.  I may add some logging to show where unpm if falling back to as well

**Comment by hayes** [comment]
should be fixed in v1.3.4

**Comment by osyed** [comment]
Thanks. Removing the trailing '/' worked.
